agent:
  type: dqn
  learning_rate: 0.001
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 0.995
env:
  name: gridworld
  size: 10
verifier:
  type: reachability
  timeout_secs: 60
training:
  episodes: 1000
  max_steps_per_episode: 200
evaluation:
  adversarial_perturbation: true
  num_trials: 50